# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170211_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to=b'teachers/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
