# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='url',
            field=models.CharField(default=b'', max_length=200, verbose_name='\u89c6\u9891\u94fe\u63a5'),
        ),
    ]
