# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usercourse_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='user',
            new_name='user_name',
        ),
    ]
